### ISSUE TITLE
Unit tests fail when run by more than one user on the same machine

### ISSUE THREAD

**Issue by amadio** [cern-fts/davix#100]
Davix's unit tests create a file in `/tmp/davix-tests-tmp-file`. However, the test doesn't remove this file, so if you run the tests as another user on the same machine (i.e. as root to install davix system-wide), the file will already be there and creation of the file will fail for the second user (with permission denied, as it already exists), causing the test to get a segfault when dereferencing the `FILE` pointer [here](https://github.com/cern-fts/davix/blob/devel/test/unit/content-provider.cpp#L14), as `fopen` returns `NULL`. Debugged this last Friday with @joaopblopes.

**Comment by mpatrascoiu** [comment]
Thanks for reporting this. Something else on the list following https://github.com/cern-fts/davix/pull/99.

**Comment by joaopblopes** [comment]
Fixed with commits [f2afd3ba](https://github.com/cern-fts/davix/commit/f2afd3ba2d6a58d68fae27d2fa5b3ebff727a682) and [23a591d5](https://github.com/cern-fts/davix/commit/23a591d5607a039f002c5df9712126bfb1e40fb5).

**Comment by joaopblopes** [comment]
Closing issue.
