### ISSUE TITLE
[regression] set_target_properties called with incorrect number of arguments

### ISSUE THREAD

**Issue by yurivict** [cern-fts/davix#30]
Version 0.6.9 fails:
```
-- Looking for uuid_generate_random in uuid - not found
-- Found uuid: /usr/local/include  
CMake Error at src/CMakeLists.txt:40 (set_target_properties):
  set_target_properties called with incorrect number of arguments.


-- generate pkgconfig file for libdavix under /usr/ports/www/davix/work/davix-R_0_6_9/src/davix.pc
-- Configuring incomplete, errors occurred!
```

**Comment by gbitzes** [comment]
Thanks, indeed there's something strange going on with Finduuid.cmake, see #28
I'll be making a new release soon, stay tuned.

**Comment by gbitzes** [comment]
Sorry, this was a completely different issue!

How are you building davix? The way to generate "blessed" release tarballs has changed - run ``packaging/make-dist.sh`` from the root of the git repository, and you'll get a release tarball under ``build`` for the git commit / tag you're currently on.

**Comment by yurivict** [comment]
It's built with cmake.

It is built as any other cmake-based project: ```cd .build && {path-to-cmake}/CMakeLists && gmake```

**Comment by gbitzes** [comment]
Are you building from git, or a tarball?

If you're building from a tarball, how did you create it? The only valid way to create one is by running ``packaging/make-dist.sh``. After that, you can run cmake normally.

Try this URL: ``http://grid-deployment.web.cern.ch/grid-deployment/dms/lcgutil/tar/davix/0.6.9/davix-0.6.9.tar.gz``

**Comment by yurivict** [comment]
I download the tarball for the tag ```R_0_6_9``` from github.

**Comment by yurivict** [comment]
The tarball URL that you provided works.
So only the github tarball is faulty.
