### ISSUE TITLE
unit tests fail

### ISSUE THREAD

**Issue by yurivict** [cern-fts/davix#33]
```
Test project /usr/ports/www/davix/work/.build
    Start 1: g_test_unit_davix
1/1 Test #1: g_test_unit_davix ................***Failed    0.06 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.07 sec

The following tests FAILED:
	  1 - g_test_unit_davix (Failed)
Errors while running CTest
FAILED: CMakeFiles/test.util 
```

OS: FreeBSD 11.2

**Comment by yurivict** [comment]
https://people.freebsd.org/~yuri/g_test_unit_davix_exe.log

**Comment by yurivict** [comment]
Yes, it fails with ```0.6.8``` as well.

**Comment by yurivict** [comment]
You can install FreeBSD in the virtual machine using this ISO image: https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/11.2/FreeBSD-11.2-RELEASE-amd64-disc1.iso


From there, cd /usr/ports/www/davix && make test

**Comment by yurivict** [comment]
Also, you should check out the latest ports tree: ```svn checkout https://svn.FreeBSD.org/ports/head /usr/ports```

**Comment by gbitzes** [comment]
Fixed, thanks for the bug report!
