### ISSUE TITLE
configure fails: set_target_properties called with incorrect number of arguments.

### ISSUE THREAD

**Issue by yurivict** [cern-fts/davix#34]
```
CMake Error at src/CMakeLists.txt:40 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

This is the offending instruction:
```
set_target_properties(libdavix PROPERTIES
                            VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}
                            SOVERSION ${VERSION_MAJOR}
                            CLEAN_DIRECT_OUTPUT 1
                            OUTPUT_NAME ${OUTPUT_NAME_DAVIX})
```

Regression in version 0.7.1
FreeBSD 11.2 amd64
cmake-3.12.3

**Comment by gbitzes** [comment]
Should be the same issue as #30 - the github tarballs are not recommended, run ``packaging/make-dist.sh`` to make a good tarball. You'll find the result in ``build``.

By default, Github simply bundles the source code in the automatically generated tarballs.. I'll see if I can fix that in future releases, but for now simply run ``packaging/make-dist.sh``.

**Comment by gbitzes** [comment]
There's also ``http://grid-deployment.web.cern.ch/grid-deployment/dms/lcgutil/tar/davix/0.7.1/davix-0.7.1.tar.gz``

**Comment by gbitzes** [comment]
Ok, I figured it out: Try downloading ``davix-0.7.1.tar.gz`` from https://github.com/cern-fts/davix/releases, this should work.

**Comment by gbitzes** [comment]
Something was broken in the release scripts, that one is not good either, sorry. Only the one I uploaded on github just now should work.

**Comment by gbitzes** [comment]
The tarball in the link has been updated, feel free to download again from there.

**Comment by yurivict** [comment]
This works, thanks for fixing it!
