### ISSUE TITLE
The tarball of the 0.7.4 release has suddenly changed

### ISSUE THREAD

**Issue by yurivict** [cern-fts/davix#46]
```
fetch: http://grid-deployment.web.cern.ch/grid-deployment/dms/lcgutil/tar/davix/0.7.4/davix-0.7.4.tar.gz: size mismatch: expected 4343614, actual 4340677
```
See the full log here: http://beefy5.nyi.freebsd.org/data/120i386-default/506094/logs/davix-0.7.4.log

What happened? Did somebody hack your server?

**Comment by gbitzes** [comment]
Hi,

It seems the github-generated tarball has size 4343614, but the one on grid-deployment 4340677.. the differences are in some personal scripts used during compilation, they should not affect the result in any way.

I've made grid-deployment the same as on github, and fixing my release scripts. Thanks for the heads up!

**Comment by yurivict** [comment]
Thanks,

Existing tarballs are fingerprinted and should not be changed once published.
Otherwise, such changes trigger errors like this in the FreeBSD package builder.

Yuri
