### ISSUE TITLE
the MacPorts port

### ISSUE THREAD

**Issue by TP75** [cern-fts/davix#48]
I highly appreciate your effort in providing open source software and supporting legacy equipment like older macs the same. 

Naturally, Homebrew is a valid option. However, one may prefer the option to use the [MacPorts](https://www.macports.org/) package manager and there is a *davix port* available too.

- - -  

http://dmc.web.cern.ch/projects/davix/home - Installation - Easy Install

Please change from:

OSX: _brew install davix_

to

OSX: `brew install davix` with Homebrew or `sudo port install davix` with MacPorts

---  

Ref to https://ports.macports.org/port/davix/summary

To my own knowledge the *davix port* installs nicely on Mac OS X / macOS 10.12.6 Sierra as:

- davix @0.7.5_1 

A clean install in a fresh environment on the a.m. OS X would result in:

```
$ port installed
The following ports are currently installed:
  autoconf @2.69_5 (active)
  automake @1.16.1_1 (active)
  bzip2 @1.0.8_0 (active)
  cmake @3.15.4_0 (active)
  curl @7.66.0_0+ssl (active)
  curl-ca-bundle @7.66.0_1 (active)
  davix @0.7.5_1 (active)
  db48 @4.8.30_4 (active)
  expat @2.2.9_0 (active)
  gdbm @1.18.1_1 (active)
  gettext @0.19.8.1_2 (active)
  glib2 @2.58.3_0+x11 (active)
  gperf @3.1_0 (active)
  help2man @1.47.11_0 (active)
  icu @65.1_0 (active)
  libarchive @3.4.0_1 (active)
  libcxx @5.0.1_4 (active)
  libedit @20190324-3.1_0 (active)
  libffi @3.2.1_0 (active)
  libiconv @1.16_0 (active)
  libidn2 @2.2.0_0 (active)
  libpsl @0.21.0-20190419_0 (active)
  libtool @2.4.6_6 (active)
  libunistring @0.9.10_0 (active)
  libuv @1.33.1_0 (active)
  libxml2 @2.9.9_3 (active)
  lz4 @1.9.2_0 (active)
  lzo2 @2.10_0 (active)
  ncurses @6.1_0 (active)
  openssl @1.1.1d_0 (active)
  p5.28-locale-gettext @1.70.0_0 (active)
  pcre @8.43_0 (active)
  perl5 @5.26.1_0+perl5_28 (active)
  perl5.28 @5.28.2_0 (active)
  pkgconfig @0.29.2_0 (active)
  python3_select @0.0_1 (active)
  python37 @3.7.5_1 (active)
  python_select @0.3_8 (active)
  readline @8.0.000_0 (active)
  sqlite3 @3.30.1_0 (active)
  texinfo @6.7_0 (active)
  xz @5.2.4_0 (active)
  zlib @1.2.11_0 (active)
  zstd @1.4.3_0 (active)
```
Hope this helps.

- - -  

Happy hacking. :+1:

**Comment by gbitzes** [comment]
Thanks for letting us know! I've updated the documentation.
