### ISSUE TITLE
Return value of `DavFile::get` is -1 but no error is thrown

### ISSUE THREAD

**Issue by mxxo** [cern-fts/davix#69]
Hello, 

I would like to use `DavFile::get` to download some files. For the few cases I have tried it seems that `DavFile::get` returns -1 instead of the number of bytes read, but as far as I can tell, the read succeeds and no `DavixError` is thrown. I wanted to ask if I am indeed making an error here.

e.g.
```cpp
#include <davix.hpp>
#include <iostream>
#include <vector>

int main() {
   Davix::Context c;
   Davix::RequestParams p;
   Davix::DavFile file(c, p, Davix::Uri("https://root.cern/files/LHCb002_data_v1.root"));

   std::vector<char> buf;
   auto ret = file.get(nullptr, buf);
   // file size is 11461 B
   if (buf.size() != 11461) {
      std::cout << "expected 11461 bytes read, got " << buf.size() << "\n";
   }
   std::cout << "got ret: " << ret << "\n";
   return 0;
}
```
prints 
```
got ret: -1
```
Thank you very much for your time.

Setup
* davix built from source, `devel` branch
* Ubuntu 18.04

**Comment by mpatrascoiu** [comment]
Hello,

I also had a look at the `DavixFile::get(..)` function and came up to the same problem as outlined in MergeRequest #70.

Many thanks for reporting and fixing this!

Cheers,
Mihai
