### ISSUE TITLE
The role of the different branches is unclear

### ISSUE THREAD

**Issue by paulmillar** [cern-fts/davix#91]
Hi,

In most projects I've seen, new features are committed to the `master` branch.  Although this repo has a `master` branch, it seems that work is mostly committed to the `devel` branch.

I think it would help if there was some documentation (perhaps the `README.md` file) that included a brief description on how the different branches are used.

Cheers,
Paul.

**Comment by mpatrascoiu** [comment]
Hello Paul,

We use a simplified version of the [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/) model.

But point taken, the [Readme > Development](https://github.com/cern-fts/davix#development) section has been updated with the Git branching model details.

Cheers,
Mihai
