### ISSUE TITLE
Copyrighted song lyrics in codebase

### ISSUE THREAD

**Issue by Nicd** [cern-fts/davix#97]
In https://github.com/cern-fts/davix/blob/454950a9b7fd35b2460318e1a0e9940af65a0996/test/unit/response-buffer.cpp#L136 the lyrics of Rick Astley's hit song [Never Gonna Give You Up](https://www.youtube.com/watch?v=dQw4w9WgXcQ) are used. As far as I know, the song lyrics have not been released under a free license. The file copyright statement also claims that the whole file is © Cern which is at odds with the inclusion of the lyrics.

Related issue in the Debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1012467

**Comment by mpatrascoiu** [comment]
Thank you for mentioning this.

We are taking the right steps to address it.

Best Regards,
Mihai

**Comment by mpatrascoiu** [comment]
Thank you again for reporting it.

Clearly, the intention was not to use the lyrics in an unauthorized manner.
The use of the lyrics has been removed from the repository and its history.

Closing this ticket.
